### PR TITLE
Oakvar CWL workflow

### PR DESCRIPTION
**Pull request by gehadkamel**

### CODE REVIEW

**Comment by rkimoakbioinformatics** [comment]
`nextflow run ov_setup.nf` does not run because `--email` and `--pw` appear without any value.

**Comment by gehadkamel** [comment]
Yes you should adjust the variables within the script or provide them as CL arguments `nextflow run ov_setup.nf - - email yourmail@example.com - - pw your_pw`

**Comment by rkimoakbioinformatics** [comment]
Got it. Can the script exit after an error message if email and password are not given in the script nor as arguments?

**Comment by gehadkamel** [comment]
Well I adjusted the script to echo for the user to give email and pw values whether in the script or as a command line argument, you may check it

**Comment by rkimoakbioinformatics** [comment]
That works. I notice that ov_run.df has outputdir parameter. If it is not given, the run fails. Shouldn't it have a similar error message about --outputdir?

**Comment by gehadkamel** [comment]
yes, but if we didn't provide the output directory it is inconvenient for the user as the output files would be retained in the work directory of  Nextflow; which is a directory that is supposed to be cleaned after the execution. So, I adjusted the output dir to be by default the current directory where the script run `params.outputdir = "."` , you may check the updated script.

**Pull request merged**
